### ISSUE TITLE
dfu-util: File size is too big: Success

### ISSUE THREAD

**Issue by LoucaFrss** [nw-rs/rustworks#12]
Hello, I'm trying to use rustworks on my numworks (n110) from my Raspberry Pi 4 (with Raspberry Pi OS, I don't know if it matters) but when I run `cargo make dfu`
I get the following error message:
```
[cargo-make] INFO - Execute Command: "dfu-util" "-d" "0483:df11" "-a" "0" "-s" "0x08000000:leave" "-D" "target/thumbv7em-none-eabihf/debug/rustworks.bin"
dfu-util 0.9

Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2016 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to http://sourceforge.net/p/dfu-util/tickets/

dfu-util: File size is too big: Success
[cargo-make] ERROR - Error while executing command, exit code: 74
[cargo-make] WARN - Build Failed.
```

Before running rustworks, I installed dependencies:
```
rustup target add thumbv7em-none-eabihf
sudo apt-get install gcc-arm-none-eabi binutils-arm-none-eabi 
sudo apt-get install dfu-util

rustup component add llvm-tools-preview
cargo install cargo-binutils
cargo install cargo-make
```

Then I cloned  rustworks repository and ran `cargo make dfu` .

The bin file (`target/thumbv7em-none-eabihf/debug/rustworks.bin`) has a size of 2, 28 GB which seems effectively too big to flash on the numworks.

did I do something wrong?

**Comment by willemml** [comment]
The master branch is currently not the latest working branch, check out the `split` branch which has the latest code and it should work (run the same commands inside the `bootloader` directory).
