### ISSUE TITLE
Matrix community?

### ISSUE THREAD

**Issue by uranuspucksaxophone** [nw-rs/rustworks#15]
https://app.element.io
https://matrix.org

**Comment by willemml** [comment]
I have create matrix communities for my other projects in the past, but usually only me and one other person end up being part of those. I can create one for this if you want.

There is also a dedicated channel for rustworks in the [Omega](https://getomega.dev/) Discord server. This is not an official rustworks Discord server but it is currently the only active place of discussion for rustworks developers besides here on GitHub.

**Comment by willemml** [comment]
Sidenote: I also want to explore GitHub discussions.

**Comment by willemml** [comment]
Closing for now as there are already places to discuss this project (GitHub discussions, Omega Discord server and unofficial matrix community).
